"""create odm report table

Revision ID: 05efb1d4f221
Revises: f529b1c90a63
Create Date: 2025-08-19 20:54:13.940809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05efb1d4f221'
down_revision: Union[str, Sequence[str], None] = 'f529b1c90a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odm_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odm_project_id', sa.Integer(), nullable=False),
    sa.Column('odm_task_id', sa.String(length=64), nullable=False),
    sa.Column('odm_host', sa.String(length=255), nullable=True),
    sa.Column('algo_name', sa.String(length=64), nullable=False),
    sa.Column('output_dir', sa.String(length=255), nullable=True),
    sa.Column('log_file', sa.String(length=255), nullable=True),
    sa.Column('orthophoto_tif', sa.String(length=255), nullable=True),
    sa.Column('area_mu', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('stddev', sa.Float(), nullable=True),
    sa.Column('output_files', sa.JSON(), nullable=True),
    sa.Column('class_count', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('err_msg', sa.String(length=255), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odm_project_id', 'odm_task_id', 'algo_name', name='uq_r_project_task_algo')
    )
    op.create_index('idx_r_celery_task_id', 'odm_reports', ['celery_task_id'], unique=False)
    op.create_index('idx_r_project_task', 'odm_reports', ['odm_project_id', 'odm_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_r_project_task', table_name='odm_reports')
    op.drop_index('idx_r_celery_task_id', table_name='odm_reports')
    op.drop_table('odm_reports')
    # ### end Alembic commands ###
