"""Job table add Column score, level,status

Revision ID: 0b1857aae626
Revises: 2be9eec66e37
Create Date: 2025-07-24 20:13:56.278606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1857aae626'
down_revision: Union[str, Sequence[str], None] = '2be9eec66e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('job', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('job', sa.Column('level', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'level')
    op.drop_column('job', 'score')
    op.drop_column('job', 'status')
    # ### end Alembic commands ###
