"""create odm table

Revision ID: 194b97582287
Revises: 0b1857aae626
Create Date: 2025-08-21 18:58:02.446930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194b97582287'
down_revision: Union[str, Sequence[str], None] = '0b1857aae626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odm_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=16), nullable=False),
    sa.Column('odm_project_id', sa.Integer(), nullable=False),
    sa.Column('odm_task_id', sa.String(length=64), nullable=False),
    sa.Column('odm_job_name', sa.String(length=255), nullable=False),
    sa.Column('odm_job_type', sa.String(length=16), nullable=False),
    sa.Column('odm_src_folder', sa.String(length=255), nullable=False),
    sa.Column('odm_dest_folder', sa.String(length=255), nullable=False),
    sa.Column('odm_samplinge_time', sa.DateTime(), nullable=True),
    sa.Column('odm_host', sa.String(length=255), nullable=False),
    sa.Column('odm_image_count', sa.Integer(), nullable=False),
    sa.Column('odm_create_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('err_msg', sa.String(length=255), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odm_project_id', 'odm_task_id', name='uq_project_task')
    )
    op.create_index('idx_celery_task_id', 'odm_jobs', ['celery_task_id'], unique=False)
    op.create_index('idx_project_task', 'odm_jobs', ['odm_project_id', 'odm_task_id'], unique=False)
    op.create_index(op.f('ix_odm_jobs_run_id'), 'odm_jobs', ['run_id'], unique=True)
    op.create_table('odm_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('algo_name', sa.String(length=64), nullable=False),
    sa.Column('output_dir', sa.String(length=255), nullable=True),
    sa.Column('log_file', sa.String(length=255), nullable=True),
    sa.Column('orthophoto_tif', sa.String(length=255), nullable=True),
    sa.Column('area_mu', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('stddev', sa.Float(), nullable=True),
    sa.Column('output_files', sa.JSON(), nullable=True),
    sa.Column('class_count', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('err_msg', sa.String(length=255), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['odm_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'algo_name', name='uq_r_project_task_algo')
    )
    op.create_index('idx_r_celery_task_id', 'odm_reports', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_odm_reports_job_id'), 'odm_reports', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odm_reports_job_id'), table_name='odm_reports')
    op.drop_index('idx_r_celery_task_id', table_name='odm_reports')
    op.drop_table('odm_reports')
    op.drop_index(op.f('ix_odm_jobs_run_id'), table_name='odm_jobs')
    op.drop_index('idx_project_task', table_name='odm_jobs')
    op.drop_index('idx_celery_task_id', table_name='odm_jobs')
    op.drop_table('odm_jobs')
    # ### end Alembic commands ###
