"""add column sample_plot in odm_jobs table

Revision ID: 1c48695815d4
Revises: 750d468cc4bb
Create Date: 2026-03-03 10:32:35.073873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c48695815d4'
down_revision: Union[str, Sequence[str], None] = '750d468cc4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odm_jobs', sa.Column('sample_plot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odm_jobs', 'sample_plot')
    # ### end Alembic commands ###
