"""init

Revision ID: 2be9eec66e37
Revises: 
Create Date: 2025-07-21 17:40:25.972643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be9eec66e37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=16), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('images_dir', sa.String(length=255), nullable=False),
    sa.Column('output_dir', sa.String(length=255), nullable=False),
    sa.Column('log_file', sa.String(length=255), nullable=False),
    sa.Column('images_total_num', sa.Integer(), nullable=False),
    sa.Column('images_detect_num', sa.Integer(), nullable=True),
    sa.Column('gsd', sa.Float(), nullable=False),
    sa.Column('row_spacing', sa.Float(), nullable=False),
    sa.Column('plant_spacing', sa.Float(), nullable=False),
    sa.Column('ridge_spacing', sa.Float(), nullable=True),
    sa.Column('big_threshold', sa.Float(), nullable=False),
    sa.Column('small_threshold', sa.Float(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('area_mu', sa.Float(), nullable=True),
    sa.Column('num_big', sa.Integer(), nullable=True),
    sa.Column('num_medium', sa.Integer(), nullable=True),
    sa.Column('num_small', sa.Integer(), nullable=True),
    sa.Column('num_total', sa.Integer(), nullable=True),
    sa.Column('num_of_per_mu', sa.Integer(), nullable=True),
    sa.Column('num_of_picture_mu', sa.Integer(), nullable=True),
    sa.Column('big_ratio', sa.Float(), nullable=True),
    sa.Column('medium_ratio', sa.Float(), nullable=True),
    sa.Column('samll_ratio', sa.Float(), nullable=True),
    sa.Column('total_ratio', sa.Float(), nullable=True),
    sa.Column('vaild_ratio', sa.Float(), nullable=True),
    sa.Column('avg_pixel_area', sa.Float(), nullable=True),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_run_id'), 'job', ['run_id'], unique=True)
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('output', sa.String(length=255), nullable=False),
    sa.Column('output_image_url', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filemd5', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('area_mu', sa.Float(), nullable=True),
    sa.Column('num_of_picture_mu', sa.Integer(), nullable=True),
    sa.Column('num_of_per_mu', sa.Integer(), nullable=True),
    sa.Column('num_total', sa.Integer(), nullable=True),
    sa.Column('num_big', sa.Integer(), nullable=True),
    sa.Column('num_medium', sa.Integer(), nullable=True),
    sa.Column('num_small', sa.Integer(), nullable=True),
    sa.Column('big_ratio', sa.Float(), nullable=True),
    sa.Column('medium_ratio', sa.Float(), nullable=True),
    sa.Column('samll_ratio', sa.Float(), nullable=True),
    sa.Column('total_ratio', sa.Float(), nullable=True),
    sa.Column('vaild_ratio', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_index(op.f('ix_job_run_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
