"""create 3dcm table

Revision ID: 5f07e8cb2616
Revises: 605c0e2dea9f
Create Date: 2025-10-17 18:20:54.639950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f07e8cb2616'
down_revision: Union[str, Sequence[str], None] = '605c0e2dea9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vdcm_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('src_path', sa.String(length=255), nullable=False),
    sa.Column('dest_path', sa.String(length=255), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('sample_number', sa.String(length=16), nullable=False),
    sa.Column('sample_batch_number', sa.String(length=16), nullable=False),
    sa.Column('image_total', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('potree_js', sa.String(length=255), nullable=True),
    sa.Column('report_ply', sa.String(length=255), nullable=True),
    sa.Column('err_msg', sa.JSON(), nullable=True),
    sa.Column('log_file', sa.String(length=255), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('reports', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vdcm_jobs_no'), 'vdcm_jobs', ['no'], unique=True)
    op.create_table('vdcm_jobs_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.Integer(), nullable=True),
    sa.Column('source_ply', sa.String(length=255), nullable=True),
    sa.Column('ply_cloud_js', sa.String(length=255), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('log_file', sa.String(length=255), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['vdcm_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vdcm_jobs_uploads_job_id'), 'vdcm_jobs_uploads', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vdcm_jobs_uploads_job_id'), table_name='vdcm_jobs_uploads')
    op.drop_table('vdcm_jobs_uploads')
    op.drop_index(op.f('ix_vdcm_jobs_no'), table_name='vdcm_jobs')
    op.drop_table('vdcm_jobs')
    # ### end Alembic commands ###
