"""create odm_generate_task table

Revision ID: 605c0e2dea9f
Revises: 194b97582287
Create Date: 2025-08-25 14:13:26.746240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605c0e2dea9f'
down_revision: Union[str, Sequence[str], None] = '194b97582287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odm_generate_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('orthophoto_tif', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('err_msg', sa.String(length=255), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['odm_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odm_generate_task_job_id'), 'odm_generate_task', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odm_generate_task_job_id'), table_name='odm_generate_task')
    op.drop_table('odm_generate_task')
    # ### end Alembic commands ###
