"""adjusted odm report tables

Revision ID: 81d8e7772333
Revises: 5f07e8cb2616
Create Date: 2025-10-29 19:25:08.981466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '81d8e7772333'
down_revision: Union[str, Sequence[str], None] = '5f07e8cb2616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odm_vegetation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('algo_name', sa.String(length=64), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('stddev', sa.Float(), nullable=True),
    sa.Column('output_files', sa.JSON(), nullable=True),
    sa.Column('class_count', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['odm_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'algo_name', name='uq_r_project_task_algo')
    )
    op.create_index(op.f('ix_odm_vegetation_job_id'), 'odm_vegetation', ['job_id'], unique=False)
    op.add_column('odm_jobs', sa.Column('radiometric', sa.JSON(), nullable=True))
    op.add_column('odm_reports', sa.Column('band', sa.JSON(), nullable=True))
    op.drop_index('idx_r_celery_task_id', table_name='odm_reports')
    with op.batch_alter_table('odm_reports') as batch_op:
        batch_op.drop_constraint('uq_r_project_task_algo', type_='unique')
    op.drop_index('ix_odm_reports_job_id', table_name='odm_reports')
    op.create_index(op.f('ix_odm_reports_job_id'), 'odm_reports', ['job_id'], unique=True)
    op.create_index(op.f('ix_odm_reports_celery_task_id'), 'odm_reports', ['celery_task_id'], unique=False)
    op.drop_column('odm_reports', 'mean')
    op.drop_column('odm_reports', 'algo_name')
    op.drop_column('odm_reports', 'max_value')
    op.drop_column('odm_reports', 'class_count')
    op.drop_column('odm_reports', 'stddev')
    op.drop_column('odm_reports', 'min_value')
    op.drop_column('odm_reports', 'output_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odm_reports', sa.Column('output_files', sqlite.JSON(), nullable=True))
    op.add_column('odm_reports', sa.Column('min_value', sa.FLOAT(), nullable=True))
    op.add_column('odm_reports', sa.Column('stddev', sa.FLOAT(), nullable=True))
    op.add_column('odm_reports', sa.Column('class_count', sqlite.JSON(), nullable=True))
    op.add_column('odm_reports', sa.Column('max_value', sa.FLOAT(), nullable=True))
    op.add_column('odm_reports', sa.Column('algo_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('odm_reports', sa.Column('mean', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_odm_reports_celery_task_id'), table_name='odm_reports')
    op.drop_index(op.f('ix_odm_reports_job_id'), table_name='odm_reports')
    op.create_index('ix_odm_reports_job_id', 'odm_reports', ['job_id'], unique=False)
    with op.batch_alter_table('odm_reports') as batch_op:
        batch_op.create_unique_constraint('uq_r_project_task_algo', ['job_id', 'algo_name'])
    op.create_index('idx_r_celery_task_id', 'odm_reports', ['celery_task_id'], unique=False)
    op.drop_column('odm_reports', 'band')
    op.drop_column('odm_jobs', 'radiometric')
    op.drop_index(op.f('ix_odm_vegetation_job_id'), table_name='odm_vegetation')
    op.drop_table('odm_vegetation')
    # ### end Alembic commands ###
