"""add column sort_no in odm_quadrat table

Revision ID: 983b4643fb7f
Revises: 1c48695815d4
Create Date: 2026-04-07 19:25:56.926821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983b4643fb7f'
down_revision: Union[str, Sequence[str], None] = '1c48695815d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_task_unique', 'odm_jobs', ['odm_project_id', 'odm_task_id'], unique=True)
    op.add_column('odm_quadrat', sa.Column('sort_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odm_quadrat', 'sort_no')
    op.drop_index('idx_project_task_unique', table_name='odm_jobs')
