"""add quadrat statistics table

Revision ID: ccb413dbdf80
Revises: 81d8e7772333
Create Date: 2025-11-12 17:22:27.647991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb413dbdf80'
down_revision: Union[str, Sequence[str], None] = '81d8e7772333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odm_sampling_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('cloud_id', sa.Integer(), nullable=True),
    sa.Column('latest_run_id', sa.String(length=16), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['odm_jobs.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['odm_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odm_sampling_records_job_id'), 'odm_sampling_records', ['job_id'], unique=False)
    op.create_index(op.f('ix_odm_sampling_records_latest_run_id'), 'odm_sampling_records', ['latest_run_id'], unique=False)
    op.create_index(op.f('ix_odm_sampling_records_report_id'), 'odm_sampling_records', ['report_id'], unique=False)
    op.create_table('odm_quadrat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sampling_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('coords', sa.JSON(), nullable=False),
    sa.Column('center', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sampling_id'], ['odm_sampling_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odm_quadrat_run_id'), 'odm_quadrat', ['run_id'], unique=False)
    op.create_index(op.f('ix_odm_quadrat_sampling_id'), 'odm_quadrat', ['sampling_id'], unique=False)
    op.create_table('odm_quadrat_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quadrat_id', sa.Integer(), nullable=False),
    sa.Column('algo_name', sa.String(length=64), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('dn_min', sa.Float(), nullable=True),
    sa.Column('dn_max', sa.Float(), nullable=True),
    sa.Column('dn_mean', sa.Float(), nullable=True),
    sa.Column('dn_std', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quadrat_id'], ['odm_quadrat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quadrat_algo', 'odm_quadrat_statistics', ['quadrat_id', 'algo_name'], unique=True)
    op.create_index(op.f('ix_odm_quadrat_statistics_quadrat_id'), 'odm_quadrat_statistics', ['quadrat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odm_quadrat_statistics_quadrat_id'), table_name='odm_quadrat_statistics')
    op.drop_index('idx_quadrat_algo', table_name='odm_quadrat_statistics')
    op.drop_table('odm_quadrat_statistics')
    op.drop_index(op.f('ix_odm_quadrat_sampling_id'), table_name='odm_quadrat')
    op.drop_index(op.f('ix_odm_quadrat_run_id'), table_name='odm_quadrat')
    op.drop_table('odm_quadrat')
    op.drop_index(op.f('ix_odm_sampling_records_report_id'), table_name='odm_sampling_records')
    op.drop_index(op.f('ix_odm_sampling_records_latest_run_id'), table_name='odm_sampling_records')
    op.drop_index(op.f('ix_odm_sampling_records_job_id'), table_name='odm_sampling_records')
    op.drop_table('odm_sampling_records')
    # ### end Alembic commands ###
