"""Job table add Column score, level

Revision ID: d6fafbb6e061
Revises: 2be9eec66e37
Create Date: 2025-07-24 11:45:27.064679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fafbb6e061'
down_revision: Union[str, Sequence[str], None] = '2be9eec66e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('job', sa.Column('level', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'level')
    op.drop_column('job', 'score')
    # ### end Alembic commands ###
