"""create rsdm table

Revision ID: f529b1c90a63
Revises: 0b1857aae626
Create Date: 2025-08-17 15:08:15.717575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f529b1c90a63'
down_revision: Union[str, Sequence[str], None] = '0b1857aae626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsdm_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=16), nullable=False),
    sa.Column('odm_project_id', sa.Integer(), nullable=False),
    sa.Column('odm_task_id', sa.String(length=64), nullable=False),
    sa.Column('odm_job_name', sa.String(length=255), nullable=False),
    sa.Column('odm_job_type', sa.String(length=16), nullable=False),
    sa.Column('odm_src_folder', sa.String(length=255), nullable=False),
    sa.Column('odm_dest_folder', sa.String(length=255), nullable=False),
    sa.Column('odm_samplinge_time', sa.DateTime(), nullable=True),
    sa.Column('odm_host', sa.String(length=255), nullable=False),
    sa.Column('odm_image_count', sa.Integer(), nullable=False),
    sa.Column('odm_create_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('err_msg', sa.String(length=255), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odm_project_id', 'odm_task_id', name='uq_project_task')
    )
    op.create_index('idx_celery_task_id', 'rsdm_jobs', ['celery_task_id'], unique=False)
    op.create_index('idx_project_task', 'rsdm_jobs', ['odm_project_id', 'odm_task_id'], unique=False)
    op.create_index(op.f('ix_rsdm_jobs_run_id'), 'rsdm_jobs', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rsdm_jobs_run_id'), table_name='rsdm_jobs')
    op.drop_index('idx_project_task', table_name='rsdm_jobs')
    op.drop_index('idx_celery_task_id', table_name='rsdm_jobs')
    op.drop_table('rsdm_jobs')
    # ### end Alembic commands ###
